name: SW_svile
author: svile fixed by misael38
description: SkyWars plugin
main: svile\sw\SWmain
version: 0.6
api: [3.5.1, 3.5.2, 3.5.3]
load: STARTUP

commands:
 sw:
  description: All Main Command Skywars Command!
